services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    ports:
      - ${PORT:-30090}:9696
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-Australia/Brisbane}
    volumes:
      - ${DATA_PATH}/prowlarr/config:/config
    networks:
      - homelab-network
    # Add healthcheck to verify config directory is available
    healthcheck:
      test: ["CMD", "test", "-d", "/config"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  homelab-network:
    external: true 